sudo: required
dist: xenial

language: bash

addons:
  apt:
    update: true

git:
  quiet: true

script:
  - sudo bash template.sh
  - sudo bash template.sh --argument1
  - sudo bash template.sh --args argument